// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfUvnVXUOAasEbX6xmoS5o4aPkp6J-ww',
    appId: '1:997714417200:web:835ebfd6b1826c8dc63ff5',
    messagingSenderId: '997714417200',
    projectId: 'activity-12-database',
    authDomain: 'activity-12-database.firebaseapp.com',
    storageBucket: 'activity-12-database.firebasestorage.app',
    measurementId: 'G-NDS022WHE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNk61nfya3TsJJdRPvel6qQ3pFLwrGV8',
    appId: '1:997714417200:android:ac36830565750bcac63ff5',
    messagingSenderId: '997714417200',
    projectId: 'activity-12-database',
    storageBucket: 'activity-12-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1nVIusbHVezQZ07S1mOto24QJ0QDw_Q',
    appId: '1:997714417200:ios:e6238b6537155aa2c63ff5',
    messagingSenderId: '997714417200',
    projectId: 'activity-12-database',
    storageBucket: 'activity-12-database.firebasestorage.app',
    iosBundleId: 'com.example.suryaActivity12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1nVIusbHVezQZ07S1mOto24QJ0QDw_Q',
    appId: '1:997714417200:ios:e6238b6537155aa2c63ff5',
    messagingSenderId: '997714417200',
    projectId: 'activity-12-database',
    storageBucket: 'activity-12-database.firebasestorage.app',
    iosBundleId: 'com.example.suryaActivity12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfUvnVXUOAasEbX6xmoS5o4aPkp6J-ww',
    appId: '1:997714417200:web:57acbc2be338d1a2c63ff5',
    messagingSenderId: '997714417200',
    projectId: 'activity-12-database',
    authDomain: 'activity-12-database.firebaseapp.com',
    storageBucket: 'activity-12-database.firebasestorage.app',
    measurementId: 'G-JDEYYETF61',
  );
}
